version: '3.8'

services:
  php:
    build: ./docker/php
    ports:
      - "${PHP_FPM_HOST_PORT-9000}:9000"
    volumes:
      # configurations
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      # program files
      - ./:/var/thinkhuge/
    depends_on:
      - db
    environment:
      - PHP_IDE_CONFIG=serverName=thinkhuge.test

  nginx:
    image: nginx:alpine
    ports:
      - '${NGINX_HOST_PORT:-80}:80'
    volumes:
      - ./docker/nginx/vhost:/etc/nginx/conf.d
      - ./:/var/thinkhuge/
    depends_on:
      - php

  db:
    build: ./docker/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=thinkhuge
      - MYSQL_USER=thinkhuge
      - MYSQL_DATABASE=thinkhuge
      - MARIADB_DATABASE=thinkhuge
    volumes:
      - ./docker/init/sql/:/docker-entrypoint-initdb.d/
      - ./docker/data/sql/:/var/lib/mysql/
    ports:
      - "${MARIADB_HOST_PORT-3306}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: "${MARIA_PORT_HOST-3306}"
      PMA_USER: thinkhuge
      PMA_PASSWORD: thinkhuge
      UPLOAD_LIMIT: 300M
    ports:
      - "${PMA_HOST_PORT-8080}:80"
    depends_on:
      - db
    restart: unless-stopped

